# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Learning from Machine Learning
author:
  name: Seth Levine
  email: levine.seth.p (at) gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A machine learning podcast that explores more than just algorithms and data: Life lessons from the experts.
baseurl: "/learning-from-machine-learning" # the subpath of your site, e.g. /blog
url: "https://splevine.github.io" # the base hostname & protocol for your site, e.g. http://example.com
minima:
  social_links:
    - title: Subscribe on YouTube
      icon: youtube
      url: "https://www.youtube.com/channel/UCGwSWuvSRzop4ZVG2z9NmnQ?sub_confirmation=1"
    - title: Follow on Twitter
      icon: twitter
      url: "https://twitter.com/nlp_nerd"
    - title: Connect on LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/sethplevine"
    - title: Listen on RSS.com
      icon: rss
      url: "https://rss.com/podcasts/learning-from-machine-learning/"
  show_excerpts: true
  date_format: "%B %-d, %Y"
  skin: auto
  nav_pages:
    - about.markdown
    - episodes.md


# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - AUTOMATION_SETUP.md
  - scripts/
  - .github/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
