name: Update Episodes

on:
  workflow_dispatch: # Manual trigger only

jobs:
  update-episodes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install requests feedparser python-dateutil pyyaml

    - name: Update episodes
      env:
        YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}
        PODCAST_RSS_URL: ${{ secrets.PODCAST_RSS_URL }}
        SUBSTACK_RSS_URL: ${{ secrets.SUBSTACK_RSS_URL }}
      run: python scripts/update_episodes_no_api.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add _posts/
        if git diff --staged --quiet; then
          echo "📭 No new episodes to add"
        else
          echo "✅ New episode(s) found - committing changes"
          git commit -m "Add new episode(s) from RSS feeds"
          git push
        fi
